# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print (np.__version__)

1.14.2


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
a = np.zeros(10)
print(a.size * a.itemsize)

80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
a = np.arange(20)
a = a[::-1]
a

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
non_zero = np.nonzero([1,2,0,0,4,0])
non_zero

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
np.random.random((3,3,3))

array([[[0.78168087, 0.15855836, 0.69959346],
        [0.71506057, 0.04718971, 0.082064  ],
        [0.19090761, 0.22081017, 0.77386607]],

       [[0.12810745, 0.02006168, 0.74072526],
        [0.97400099, 0.80553871, 0.69530619],
        [0.89691349, 0.91273848, 0.83083848]],

       [[0.34725686, 0.08112651, 0.19269469],
        [0.48618467, 0.38248256, 0.9576524 ],
        [0.07176497, 0.79951071, 0.21205441]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
a = np.random.random((10,10))
min = a.min()
max = a.max()
min, max

(0.0062674264061404195, 0.9799983383010696)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
a = np.random.random(30)
a.mean()

0.5653707735051374

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
a = np.ones((5,5))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
a = np.ones((5,5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
a = np.diag(1 + np.arange(4),k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
a = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
a = np.random.random((5,5))
max = a.max()
min = a.min()
a = (a - min)/(max - min)
print(a)

[[0.72778585 0.27841765 0.10316462 0.39164735 0.21759559]
 [0.17689632 0.55636645 0.8429271  0.15647603 0.61256646]
 [0.40944366 0.80567362 0.43222926 0.70799992 1.        ]
 [0.16462677 0.49603329 0.28226142 0.28592038 0.48696493]
 [0.6347908  0.42853034 0.20235808 0.         0.25919537]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
a = np.ones((5,3)) @ np.ones((3,2))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
a = np.arange(11)
print(a)
a[(3 < a) & (a <= 8)] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
Z = np.arange(11)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print("Z<Z>Z can't be calcualted")

[          1           1           4          27         256        3125
       46656      823543    16777216   387420489 10000000000]
[  0   1   2   4   8  16  32  64 128 256 512]
[False False False False False False False False False False False]
[0. +0.j 0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j
 0. +9.j 0.+10.j]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Z<Z>Z can't be calcualted


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
a = np.random.uniform(-10,+10,10)
print(a)
np.copysign(np.ceil(np.abs(a)), a)

[ 0.6358512  -2.18959112 -5.54835801  2.6633683  -3.19448857  9.67013061
 -4.54347189 -3.66933969 -1.63385313 -2.89895695]


array([ 1., -3., -6.,  3., -4., 10., -5., -4., -2., -3.])

#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(a)
print(b)
np.intersect1d(a,b)

[8 4 3 6 4 0 5 2 3 8]
[6 3 8 7 1 0 3 1 3 4]


array([0, 3, 4, 6, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
defaults = np.seterr(all="ignore")
np.ones(5) / 0

array([inf, inf, inf, inf, inf])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2018-04-17 2018-04-18 2018-04-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [36]:
a = np.random.uniform(0,10,10)
print (np.floor(a))
print (a.astype(int))
print (a - a%1)
print (np.ceil(a) - 1)
print (np.trunc(a))

[7. 6. 6. 8. 2. 0. 2. 2. 2. 8.]
[7 6 6 8 2 0 2 2 2 8]
[7. 6. 6. 8. 2. 0. 2. 2. 2. 8.]
[7. 6. 6. 8. 2. 0. 2. 2. 2. 8.]
[7. 6. 6. 8. 2. 0. 2. 2. 2. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
a = np.zeros((5,5))
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(),dtype=float,count=-1)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
a = np.random.random(10)
print(a)
a.sort()
a

[0.51331777 0.88511142 0.0153164  0.40210899 0.66966222 0.7982461
 0.42364289 0.04497517 0.25572995 0.46611566]


array([0.0153164 , 0.04497517, 0.25572995, 0.40210899, 0.42364289,
       0.46611566, 0.51331777, 0.66966222, 0.7982461 , 0.88511142])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
a = np.arange(10)
%timeit np.sum(a)
%timeit np.add.reduce(a)

6.75 µs ± 93 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.7 µs ± 150 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [42]:
A = np.random.randint(0,5,5)
B = np.random.randint(0,5,5)
print(A)
print(B)
np.array_equal(A,B)

[1 1 0 1 3]
[2 4 1 2 1]


False

#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
a = np.zeros(10)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
a = np.random.random((10,2))
X,Y = a[:,0], a[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.68411138 0.17069271 0.83422375 0.38515478 0.53428548 0.73670386
 0.73155163 1.01123374 0.12609986 0.42022714]
[0.53011707 0.07496381 1.22664267 1.53882979 0.01796846 1.2519779
 1.12659195 0.24262995 0.53671577 1.01874185]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
a = np.random.randint(1, 5, 10)
print(a)
a[a ==a.max()] = 0
print(a)

[3 2 4 2 2 3 1 4 2 3]
[3 2 0 2 2 3 1 0 2 3]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [46]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [47]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in []:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


#### 49. How to print all the values of an array? (★★☆)

In [49]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
a = np.arange(100)
u = np.random.uniform(0,100)
index = (np.abs(a - u)).argmin()
print(a[index])

15


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [52]:
z = np.random.random((10,2))
x,y = np.atleast_2d(z[:,0], z[:,1])
d = np.sqrt((x - x.T)**2 + (y - y.T)**2)
print(d)

[[0.         0.45639526 0.53705843 0.57669529 0.42970287 0.22998903
  0.37041817 0.56135675 0.64886924 0.44963317]
 [0.45639526 0.         0.51894469 0.34287258 0.4050828  0.68638127
  0.82512498 0.74005375 0.32867898 0.46643397]
 [0.53705843 0.51894469 0.         0.84622462 0.12679654 0.67624309
  0.80862863 1.07254325 0.84732694 0.87345752]
 [0.57669529 0.34287258 0.84622462 0.         0.7238357  0.77317215
  0.88202508 0.53658587 0.11284121 0.25814769]
 [0.42970287 0.4050828  0.12679654 0.7238357  0.         0.5948687
  0.73430211 0.95103049 0.73095106 0.74689028]
 [0.22998903 0.68638127 0.67624309 0.77317215 0.5948687  0.
  0.14488613 0.59512171 0.85774468 0.5925589 ]
 [0.37041817 0.82512498 0.80862863 0.88202508 0.73430211 0.14488613
  0.         0.61608016 0.97395873 0.67599277]
 [0.56135675 0.74005375 1.07254325 0.53658587 0.95103049 0.59512171
  0.61608016 0.         0.64891431 0.28888191]
 [0.64886924 0.32867898 0.84732694 0.11284121 0.73095106 0.85774468
  0.97395873 0.648914

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [53]:
a = np.arange(10, dtype=np.float32)
print(a)
a = a.astype(np.int32, copy=False)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
data = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""
from io import StringIO
s = StringIO(data)
np.genfromtxt(s, delimiter=",", dtype=np.int)

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [55]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [56]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [57]:
n = 10
p = 2
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [58]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.41057741  0.30193119 -0.3120014   0.20573455  0.2740638  -0.10241347
   0.24465688  0.3732456  -0.29013341 -0.28450632]
 [ 0.10131053 -0.24680805 -0.22421504  0.62724785 -0.13093659 -0.23524228
   0.42020946 -0.18585214 -0.01805908 -0.10765465]
 [ 0.14354713  0.1482552  -0.07223922  0.16901634 -0.20884415 -0.41278217
   0.10872746 -0.33899668  0.1960624   0.26725369]
 [ 0.23334506 -0.24448914 -0.17908953  0.57246945  0.14023001  0.18067281
  -0.20563891 -0.32495273 -0.3521483   0.17960128]
 [ 0.21418846 -0.18984386  0.14379146  0.04856928  0.43992828  0.35512157
  -0.30720554 -0.4705195  -0.24478459  0.01075444]]


#### 59. How to sort an array by the nth column? (★★☆)

In [59]:
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[6 7 6]
 [6 8 1]
 [4 1 1]]
[[4 1 1]
 [6 7 6]
 [6 8 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [60]:
a = np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [61]:
a = np.random.uniform(0,1,10)
val = 0.5
a.flat[np.abs(a - val).argmin()]

0.5299845007794822

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [62]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [63]:
class NArray(np.ndarray):
    def __new__(cls, array, name="no_name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no_name")

a = NArray(np.arange(10), "test_name")
a.name

'test_name'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [64]:
a = np.ones(10)
print(a)
b = np.random.randint(0,len(a),20)
print(b)
np.add.at(a, b, 1)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[9 7 0 2 3 6 3 1 7 0 4 4 5 2 0 5 1 7 1 8]
[4. 4. 3. 3. 3. 3. 2. 4. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [65]:
X = [1,2,3,4,5,6]
I = np.random.randint(0, 10, len(X))
F = np.bincount(X,I)
print(I)
print(F)

[8 4 2 3 7 2]
[0. 8. 4. 2. 3. 7. 2.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [66]:
w,h = 8,8
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
print(F)
n = len(np.unique(F))
print(n)

[[65536     1     0     1   256     1     0 65793]
 [65537     1 65792 65537     0   256     1   257]
 [65537   257   257 65792     0 65537     0   256]
 [65792     1 65536 65537 65793   256   257   257]
 [  257 65537   257   256 65792 65536     1 65792]
 [    0   256   257   257     1   257   256     1]
 [65537 65792   257 65792   256 65792 65536 65536]
 [65792   256   256     1 65793 65793 65793     0]]
8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [67]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)

[[51 51 50 71]
 [49 36 55 56]
 [64 56 50 51]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [68]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.34706867 0.61489907 0.32444616 0.44968937 0.52024795 0.41885276
 0.41331802 0.4494937  0.5630144  0.47679131]


#### 69. How to get the diagonal of a dot product? (★★★)

In [69]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.04984431, 0.60919218, 1.38911142, 1.12660654, 1.66162388])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [70]:
a = np.array([1,2,3,4,5])
nz = 3
a0 = np.zeros(len(a) + (len(a)-1)*(nz))
a0[::nz+1] = a
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [71]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [72]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [73]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [74]:
a = np.random.uniform(-1.0,1.0,100)
np.negative(a, out=a)
print(a)

[-0.87660542  0.01772528  0.69796612  0.11844194 -0.93383498  0.42964798
  0.34709483  0.05116478 -0.25067952 -0.54612243  0.11277046 -0.3926161
  0.19163004 -0.15765584  0.36773931 -0.14089749  0.42278095 -0.77515126
  0.22445097  0.48118676  0.84215625 -0.55322938  0.60592373 -0.6805371
  0.16197097  0.70205972  0.29550274 -0.54910677  0.7400079   0.07715591
 -0.38643545  0.60062063 -0.58238286 -0.21830834  0.22356796  0.69966837
  0.96152401  0.72571317  0.29735115  0.76127334  0.84800338  0.61662946
  0.3319869   0.01515047  0.65652422 -0.32935723 -0.72312905 -0.47570108
 -0.12383435  0.76728081  0.53144603 -0.20783439  0.82274175 -0.16813281
 -0.09868705  0.0238216   0.93248437  0.03586179  0.41312722  0.78745985
 -0.48489916 -0.1360436  -0.65439792  0.05642863 -0.26702009  0.80826793
 -0.97469837 -0.56029054 -0.95272411  0.4887765   0.93038777  0.01707783
 -0.72438097 -0.4120749  -0.4530109  -0.99099611  0.72219357 -0.99368146
 -0.09171238 -0.08923377  0.42518361  0.29854012 -0.5

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [75]:
from numpy.lib import stride_tricks

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [3]:
a = np.random.uniform(0,1,(10,10))
_, S, _ = np.linalg.svd(a)
rank = np.sum(S > 1e-10)
rank

11.584785648754533

#### 83. How to find the most frequent value in an array?

In [77]:
Z = np.random.randint(0,10,50)
np.bincount(Z).argmax()

1

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [78]:
a = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (a.shape[0]-3)
j = 1 + (a.shape[1]-3)
C = stride_tricks.as_strided(a, shape=(i, j, n, n), strides=a.strides + a.strides)
print(C)

[[[[1 4 2]
   [2 2 0]
   [3 1 2]]

  [[4 2 1]
   [2 0 1]
   [1 2 1]]

  [[2 1 3]
   [0 1 3]
   [2 1 1]]

  [[1 3 0]
   [1 3 0]
   [1 1 4]]

  [[3 0 3]
   [3 0 3]
   [1 4 2]]

  [[0 3 3]
   [0 3 3]
   [4 2 3]]

  [[3 3 1]
   [3 3 0]
   [2 3 2]]

  [[3 1 3]
   [3 0 4]
   [3 2 2]]]


 [[[2 2 0]
   [3 1 2]
   [4 3 1]]

  [[2 0 1]
   [1 2 1]
   [3 1 0]]

  [[0 1 3]
   [2 1 1]
   [1 0 3]]

  [[1 3 0]
   [1 1 4]
   [0 3 3]]

  [[3 0 3]
   [1 4 2]
   [3 3 3]]

  [[0 3 3]
   [4 2 3]
   [3 3 3]]

  [[3 3 0]
   [2 3 2]
   [3 3 1]]

  [[3 0 4]
   [3 2 2]
   [3 1 1]]]


 [[[3 1 2]
   [4 3 1]
   [4 3 1]]

  [[1 2 1]
   [3 1 0]
   [3 1 1]]

  [[2 1 1]
   [1 0 3]
   [1 1 0]]

  [[1 1 4]
   [0 3 3]
   [1 0 3]]

  [[1 4 2]
   [3 3 3]
   [0 3 4]]

  [[4 2 3]
   [3 3 3]
   [3 4 0]]

  [[2 3 2]
   [3 3 1]
   [4 0 3]]

  [[3 2 2]
   [3 1 1]
   [0 3 2]]]


 [[[4 3 1]
   [4 3 1]
   [2 2 0]]

  [[3 1 0]
   [3 1 1]
   [2 0 4]]

  [[1 0 3]
   [1 1 0]
   [0 4 1]]

  [[0 3 3]
   [1 0 3]
   [4 1 1]]

  [[3 3 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [79]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  3  9  4  5]
 [ 3  7 12  9  9]
 [ 9 12  7 42  8]
 [ 4  9 42  2 12]
 [ 5  9  8 12  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [80]:
a = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], k), axis=0),
                                       np.arange(0, a.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [81]:
a = np.arange(10000)
np.random.shuffle(a)
n = 5

print (a[np.argsort(a)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [82]:
A = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(A.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [83]:
x = np.random.rand(1000)
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

40.4 µs ± 856 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
3.77 µs ± 768 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
12 µs ± 5.27 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [84]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [85]:
A = np.random.randint(0,5,(10,3))
A[A.max(axis=1) != A.min(axis=1),:]

array([[3, 1, 2],
       [1, 1, 3],
       [0, 4, 1],
       [4, 4, 1],
       [3, 4, 1],
       [3, 2, 1],
       [0, 1, 3],
       [2, 0, 2],
       [4, 2, 1],
       [3, 0, 2]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [86]:
A = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
np.unpackbits(A[:, np.newaxis], axis=1)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [87]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.60419323, 0.39604916, 0.18303284, 0.14212382, 0.75988883,
        0.70786273, 0.87877734, 0.81751882, 0.49821308, 0.24228364],
       [0.08194733, 0.05371654, 0.02482493, 0.0192764 , 0.10306448,
        0.09600813, 0.11918945, 0.1108809 , 0.06757314, 0.03286117],
       [0.12382218, 0.08116554, 0.03751039, 0.02912658, 0.15573013,
        0.145068  , 0.1800949 , 0.1675407 , 0.10210281, 0.04965313],
       [0.24563809, 0.16101597, 0.07441301, 0.05778122, 0.308937  ,
        0.2877855 , 0.35727177, 0.33236679, 0.20255127, 0.09850175],
       [0.30592711, 0.20053547, 0.09267682, 0.07196295, 0.38476199,
        0.3584191 , 0.44495998, 0.41394235, 0.25226513, 0.12267786],
       [0.17405107, 0.11409062, 0.05272661, 0.04094187, 0.2189026 ,
        0.20391534, 0.25315103, 0.23550417, 0.14352117, 0.0697951 ],
       [0.0226085 , 0.01481989, 0.00684896, 0.00531818, 0.02843453,
        0.02648774, 0.03288325, 0.030591  , 0.0186428 , 0.00906609],
       [0.28075038, 0.1840321 , 0.0850498

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [88]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [89]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.05208608  0.30617377]
