### Losson 1

In [18]:
import numpy as np

In [19]:
a = [1., 3., 4]

In [20]:
b = np.array([1., 3., 4.])

In [21]:
type(a)

list

In [22]:
type(b)

numpy.ndarray

In [23]:
c = range(10000)

In [27]:
%%timeit
sum([x**2 for x in c])

5.08 ms ± 797 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [28]:
c_numpy = np.array(10000)

In [30]:
%%timeit
(c_numpy ** 2).sum()

2.98 µs ± 580 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [31]:
a = np.array([1., 51., 5, 8], dtype=float)

In [32]:
a

array([ 1., 51.,  5.,  8.])

In [33]:
hh = [1, 8, 9]

In [36]:
hh_array = np.array(hh, dtype=int)

In [37]:
hh_array

array([1, 8, 9])

In [40]:
np.arange(100, dtype=np.complex)

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j, 20.+0.j,
       21.+0.j, 22.+0.j, 23.+0.j, 24.+0.j, 25.+0.j, 26.+0.j, 27.+0.j,
       28.+0.j, 29.+0.j, 30.+0.j, 31.+0.j, 32.+0.j, 33.+0.j, 34.+0.j,
       35.+0.j, 36.+0.j, 37.+0.j, 38.+0.j, 39.+0.j, 40.+0.j, 41.+0.j,
       42.+0.j, 43.+0.j, 44.+0.j, 45.+0.j, 46.+0.j, 47.+0.j, 48.+0.j,
       49.+0.j, 50.+0.j, 51.+0.j, 52.+0.j, 53.+0.j, 54.+0.j, 55.+0.j,
       56.+0.j, 57.+0.j, 58.+0.j, 59.+0.j, 60.+0.j, 61.+0.j, 62.+0.j,
       63.+0.j, 64.+0.j, 65.+0.j, 66.+0.j, 67.+0.j, 68.+0.j, 69.+0.j,
       70.+0.j, 71.+0.j, 72.+0.j, 73.+0.j, 74.+0.j, 75.+0.j, 76.+0.j,
       77.+0.j, 78.+0.j, 79.+0.j, 80.+0.j, 81.+0.j, 82.+0.j, 83.+0.j,
       84.+0.j, 85.+0.j, 86.+0.j, 87.+0.j, 88.+0.j, 89.+0.j, 90.+0.j,
       91.+0.j, 92.+0.j, 93.+0.j, 94.+0.j, 95.+0.j, 96.+0.j, 97.+0.j,
       98.+0.j, 99.+

In [42]:
hh_array.shape

(3,)

In [44]:
hh_matrix = np.array([[[1,2], [5,6]], [[1,2], [5,6]]])

In [45]:
hh_matrix

array([[1, 2],
       [5, 6]])

In [46]:
hh_matrix.shape

(2, 2)

In [47]:
hh_tensor = np.array([[[1,2], [5,6]], [[1,2], [5,6]]])

In [48]:
hh_tensor

array([[[1, 2],
        [5, 6]],

       [[1, 2],
        [5, 6]]])

In [49]:
hh_tensor.shape

(2, 2, 2)

In [50]:
hh_tensor.ndim

3

In [51]:
hh_matrix.ndim

2

In [52]:
hh_array.ndim

1

In [54]:
type(hh_matrix.shape)

tuple

In [55]:
np.linspace(0, 1, num = 11 )

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [56]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.ones_like(hh_tensor)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [58]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
np.zeros_like(hh_tensor)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [61]:
np.eye(1)

array([[1.]])

In [62]:
np.eye(1).shape

(1, 1)

In [65]:
np.eye(12, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [67]:
np.diag([1, 5, 8, 9], k = 1)

array([[0, 1, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 8, 0],
       [0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0]])

In [70]:
hh_matrix

array([[1, 2],
       [5, 6]])

In [71]:
hh_matrix[0][1]

2

In [73]:
hh_matrix[1, 0]

5

In [76]:
hh_tensor[0, 0, 1]

2

In [78]:
hh_vector = np.arange(10, dtype=float)


In [80]:
hh_vector

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [81]:
hh_matrix[:, 0]

array([1, 5])

In [85]:
b = hh_vector

In [86]:
hh_vector

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [88]:
np.may_share_memory(hh_vector, b)

True

In [89]:
b = hh_vector.copy()

In [90]:
np.may_share_memory(hh_vector, b)

False

In [91]:
b[0]=10

In [92]:
hh_vector[0]

0.0

In [93]:
hh_matrix


array([[1, 2],
       [5, 6]])

In [94]:
hh_matrix.T

array([[1, 5],
       [2, 6]])

In [95]:
a = np.array([[1, 3]])
a.shape

(1, 2)

In [96]:
a.T.shape

(2, 1)

In [97]:
np.linalg.matrix_rank(hh_matrix)

2

In [98]:
hhhg = np.array([[1, 2], [3, 6]])

In [99]:
np.linalg.matrix_rank(hhhg)

1

In [100]:
hh_vector.sum()

45.0

In [102]:
hh_vector.min()

0.0

In [103]:
hh_vector.mean()

4.5

In [104]:
hh_vector.std()

2.8722813232690143

In [106]:
np.sqrt(sum([(x - 4.5)**2 for x in hh_vector])/10)

2.8722813232690143

In [107]:
hh_matrix

array([[1, 2],
       [5, 6]])

In [113]:
print(hh_matrix.sum(axis=1))
print(hh_matrix.sum(axis=0))

[ 3 11]
[6 8]


In [115]:
hh_vector.argmin()

0

In [116]:
hh_tensor.ravel()

array([1, 2, 5, 6, 1, 2, 5, 6])

In [117]:
hh_vector

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [119]:
hh_vector.reshape(5, 2)

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [120]:
np.all(hh_vector > 2)

False

In [121]:
np.any(hh_vector > 2)

True

In [122]:
hh_vector > 2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

<module 'numpy.linalg' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\linalg\\__init__.py'>